### ISSUE TITLE
[Feacture]add block blacklist!

### ISSUE THREAD

**Issue by devryb** [TheFantasyCraft/Forge-Permittor#3]
Enlightened glass from EnderIO is being registered as a container, anyway to blacklist block id's from doing this?

**Comment by thomas15v** [comment]
Sorry that I haven't seen it before. I am afraid their isn't a way to blacklist it for now. I suppose the the glass has a tileentity because it has a costum renderer. Is it gamebreaking problem?

**Comment by devryb** [comment]
Not really we just used a different type of glass for the shops. I'd be much more interested in wg6 support being added :)

**Comment by thomas15v** [comment]
Hmm lets say I add a list where you can override the automatic evaluation of items. like this
```yml
#Example blocklist
blocklist:
  #for 1.6.4 and older
  '14:8' : Container
  #for 1.7.10 and newer
  'enderio:englightendglass' : Block
#ExampleItemList
itemList:
  #for 1.6.4 and older
  '268:8' : AdvItem
  #for 1.7.10 and newer
  'fancyweaponmod:LightSaber' : Weapon
```

would that be good ? Altrough I have to say it will be for later, I am in the middle of the exams and can't really code mutch :cry:.
